# Generated by Django 4.1.7 on 2023-03-24 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='imagecategory',
            name='image',
        ),
        migrations.AddField(
            model_name='imagecategory',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imagecategory',
            name='alt',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='imagecategory',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app_catalog.category'),
        ),
    ]
