# Generated by Django 4.1.7 on 2023-03-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_alter_product_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
