# Generated by Django 4.1.7 on 2023-03-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_rename_image_imageproduct_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='authorID',
        ),
    ]
