# Generated by Django 4.1.7 on 2023-03-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0005_rename_author_review_authorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='app_products.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
