# Generated by Django 4.1.7 on 2023-03-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0006_specification_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='value',
            field=models.CharField(max_length=200, verbose_name='Значение'),
        ),
    ]
