# Generated by Django 4.1.7 on 2023-03-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0007_alter_specification_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
    ]
