# Generated by Django 4.1.7 on 2023-03-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0009_product_rating_alter_review_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limited',
            field=models.BooleanField(default=False, verbose_name='Ограниченная серия'),
        ),
    ]
