# Generated by Django 4.1.7 on 2023-04-01 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0010_product_limited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой')),
                ('dateFrom', models.DateField(auto_now_add=True, verbose_name='Начало действия')),
                ('dateTo', models.DateField(verbose_name='Конец действия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='app_products.product', verbose_name='Продукт')),
            ],
        ),
    ]
