# Generated by Django 4.1.7 on 2023-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0011_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='dateFrom',
            field=models.DateField(verbose_name='Начало действия'),
        ),
    ]
