# Generated by Django 4.1.7 on 2023-04-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0012_alter_sale_options_alter_sale_datefrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sale', serialize=False, to='app_products.product', verbose_name='Продукт'),
        ),
    ]
