# Generated by Django 4.1.7 on 2023-03-23 08:30

import app_users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[app_users.models.CustomUser.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'], message='Расширение не поддерживается. Разрешённые расширения .jpg .gif .PNG')], verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
